spring:
  application:
    name: discovery
server:
  port: 8081

application:
  version: 1.0
  author: bgimenez

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
